### ISSUE TITLE
Neue Wireframes ins Wiki aufnhemen

### ISSUE THREAD

**Issue by JohnBryanSpieker** [Archi-Lab/prox-documentation-ip-ws2019#11]
Die neu erstellten Wireframes müssen das selbe Desig haben, wie das bereits vorhandene.

Beschreibung der Wireframes wird mit dem Issue "Abgleich des Prototyps" eingepflegt.

Diese Issue ist "Done", wenn die Wireframes (ohne beschreibung) im Wiki sind.

**Comment by jlengelsen** [comment]
Issue moved to [Archi-Lab/prox-backlog-ip-ws19 #14](https://github.com/Archi-Lab/prox-backlog-ip-ws19/issues/14) via [**ZenHub**](https://www.zenhub.com/)
