### ISSUE TITLE
API-Design für Profile-Service

### ISSUE THREAD

**Issue by JohnBryanSpieker** [Archi-Lab/prox-documentation-ip-ws2019#12]
Es muss eine API designt werden (Code und Schritflich/Bild) mit allen benötigten anforderungen.
Bsp.
1. Gib mir die Daten für einen bestimmten professor.
2. Speicher eine Änderung (Professor wird aktualisiert übergeben)
3. etc.

Diese muss ebenfalls im Wiki aufgenommen werden

**Comment by jlengelsen** [comment]
Issue moved to [Archi-Lab/prox-backlog-ip-ws19 #13](https://github.com/Archi-Lab/prox-backlog-ip-ws19/issues/13) via [**ZenHub**](https://www.zenhub.com/)
