### ISSUE TITLE
Wireframe mit einzelnen Stakeholdern (Studierende, Profs) rückkoppeln

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-documentation-ip-ws2019#7]
* Bitte je Feedbacksession ein Task mit Name des konkreten Ansprechpartners
* Ergebnis im Github-Wiki dokumentieren

**Comment by jlengelsen** [comment]
Issue moved to [Archi-Lab/prox-backlog-ip-ws19 #15](https://github.com/Archi-Lab/prox-backlog-ip-ws19/issues/15) via [**ZenHub**](https://www.zenhub.com/)
